(function(o,h,f){"use strict";const{sendBotMessage:a}=h.findByProps("sendBotMessage");function y(n){return n.replace(/\[(.*?)\]/g,(i,e)=>e.trim())}function w(n){const i="https://www.urbandictionary.com/define.php?term=";return n.replace(/\[(.*?)\]/g,(e,t)=>(t=t.trim(),`[${t}](<${i+encodeURIComponent(t)}>)`))}function l(n){return`> ${n.replaceAll(`
`,`
> `)}`}async function b(n,i){try{const e=new Map(n.map(m=>[m.name,m])),t=e.get("word").value.trim(),$=encodeURIComponent(t),_=`https://api.urbandictionary.com/v0/define?term=${$}`,d=await fetch(_),k=await d.json(),v=e.get("inline_links")?.value||!1,s=k.list?.[0],c=s?.definition;if(!c)return a(i.channel.id,{content:`No definition found for \`${t.replaceAll("`","`\u{E0134}")}\`${d.status!==200?` (${d.status})`:""}`,ephemeral:!0});const u=`https://www.urbandictionary.com/define.php?term=${encodeURIComponent(s.word)}`;let r=`__Definition for **\`${s.word}\`**__`;if(v?r+=` ([source](${u}))
${l(w(c))}`:r+=`
${l(y(c))}

Source: <${u}>`,e.get("ephemeral")?.value===!1)return{content:r};a(i.channel.id,r)}catch(e){console.error(e),a(i.channel.id,{content:`An error has occurred while processing the </urban:0> command:
\`\`\`js
${e.stack}\`\`\``,ephemeral:!0})}}let p;var g={onLoad:()=>{p=f.registerCommand({name:"urbantron",displayName:"urbantron",description:"Search urban dictionary",displayDescription:"Search urban dictionary",options:[{name:"word",displayName:"word",description:"The word you want the definition for",displayDescription:"The word you want the definition for",required:!0,type:3},{name:"ephemeral",displayName:"ephemeral",description:"Make outputs only be seen by you (default: true)",displayDescription:"Make outputs only be seen by you (default: true)",type:5,required:!1},{name:"inline_links",displayName:"inline_links",description:"Makes the [highlighted] words pressable (default: false)",displayDescription:"Makes the [highlighted] words pressable (default: false)",type:5,required:!1}],execute:b,applicationId:-1,inputType:1,type:1})},onUnload:()=>{p()}};return o.default=g,Object.defineProperty(o,"__esModule",{value:!0}),o})({},vendetta.metro,vendetta.commands);
